name: Generate headers
on:
  workflow_call:
  pull_request:
  push:
    branches:
      - master
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          submodules: true
      - name: Generate headers
        run: |
          cmake -B build -DFETCHCONTENT_SOURCE_DIR_VULKAN=@ \
            -DVMA_HPP_GENERATOR_BUILD=ON -DVMA_HPP_RUN_GENERATOR=ON -DVMA_HPP_DO_UPDATE=ON -DVMA_HPP_SAMPLES_BUILD=OFF
          cmake --build build --target GenerateVmaHpp
          git diff --exit-code
